# This file is included only for launchers to display mod metadata. It is not read by Forge in production.
modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/decce6/Ixeris/issues"
license = "${mod_license}"
clientSideOnly=true

[[mods]]
modId = "ixeris_dummy"
version = "${mod_version_full}"
displayName = "${mod_name}"
displayURL = "https://modrinth.com/mod/ixeris"
logoFile="assets/ixeris/icon.png"
description = '''${mod_description}'''
authors = "${mod_author}"
credits = "LitnhJacuzzi"
