modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/decce6/Ixeris/issues"
license = "${mod_license}"
clientSideOnly=true

[[mods]]
modId = "ixeris"
version = "${mod_version_full}"
displayName = "${mod_name}"
displayURL = "https://modrinth.com/mod/ixeris"
logoFile="assets/ixeris/icon.png"
description = '''${mod_description}'''
authors = "${mod_author}"
credits = "LitnhJacuzzi"

[[dependencies.ixeris]]
modId = "forge"
mandatory = true
ordering = "NONE"
side = "BOTH"

[[dependencies.ixeris]]
modId = "minecraft"
versionRange = "${minecraft_supported_forge}"
mandatory = true