modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = ""
license = "${mod_license}"

[[mods]]
    modId = "ixeris"
    version = "${mod_version}"
    displayName = "Ixeris"
    description = '''${mod_description}'''
    authors = "${mod_author}"

[[mixins]]
    config = "ixeris.mixins.json"

[[dependencies.ixeris]]
    modId = "neoforge"
    type = "required"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.ixeris]]
    modId = "minecraft"
    type = "required"