name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew --no-daemon --no-build-cache --no-configuration-cache chiseledBuild
      - uses: actions/upload-artifact@v4
        with:
          name: Ixeris
          path: |
            versions/1.20.1-fabric/build/libs
            versions/1.20.4-fabric/build/libs
            versions/1.21.1-fabric/build/libs
            versions/latest-fabric/build/libs
#           forge/build/libs